server:
  port: 24000

app:
  web-address: http://dev.investand.com:9090
  cors:
    allowed-origins: 'http://localhost:8080,http://dev.investand.com,http://dev.investand.com:9090'

baseUrl: https://dev.investand.com:24000

springdoc:
  version: '1.0.0'
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  show-actuator: true
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

